"""
Audit Bridge - Seamless audit execution for Claude Code.

This module provides functionality to parse, validate, split, and execute
audit documents generated by Claude.ai.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

# =============================================================================
# Constants
# =============================================================================

PHASER_VERSION = "1.6.0"

SETUP_START_MARKER = "=== AUDIT SETUP START ==="
SETUP_END_MARKER = "=== AUDIT SETUP END ==="

DOCUMENT_HEADER_PATTERN = re.compile(r"^# Document (\d+):\s*(.+)$", re.MULTILINE)
PHASE_HEADER_PATTERN = re.compile(r"^## Phase (\d+):\s*(.+)$", re.MULTILINE)
COMPLETION_HEADER_PATTERN = re.compile(r"^## Document Completion", re.MULTILINE)

TOKEN_WARNING_THRESHOLD = 20000
TOKEN_ERROR_THRESHOLD = 25000

# =============================================================================
# Errors
# =============================================================================


class BridgeError(Exception):
    """Base error for bridge operations."""

    pass


class ParseError(BridgeError):
    """Error parsing audit document."""

    def __init__(self, message: str, line: int | None = None):
        self.line = line
        full_message = f"{message}" + (f" (line {line})" if line else "")
        super().__init__(full_message)


class ValidationError(BridgeError):
    """Error validating audit document structure."""

    def __init__(self, message: str, issues: list[ValidationIssue] | None = None):
        self.issues = issues or []
        super().__init__(message)


class ExecutionError(BridgeError):
    """Error executing audit."""

    pass


# =============================================================================
# Enums
# =============================================================================


class FileAction(str, Enum):
    """Action type for files in a phase."""

    CREATE = "CREATE"
    MODIFY = "MODIFY"
    DELETE = "DELETE"
